# 05 — Fetch Subscriptions

Pulls **every** subscription from MySQL (no `AccountCode` filter — this
loads the full set to be split across the two target accounts), then for
each one:

1. Decides which target account it belongs to (`resolve_target_account`,
   based on `Reference`).
2. Looks up its real address + radius username from Voyager
   (`get_voyager_address`) — `SupplierServiceID` -> `GET .../fibre/v1/circuits/{id}`
   (gives `radiusUsers[0]` + `locationId`) -> `GET .../address-search/v3/addresses/id/{locationId}`
   (gives the actual street address, city, postcode, region). Region name
   is mapped to a 3-char ISO code via `NZ_Regions.xlsx`.

This is a data-prep step that calls out to Voyager (not OneBill) — no
OneBill API calls happen here. Output feeds both `06_Create_Addresses.ipynb`
and `07_Create_Subscription_Orders.ipynb` (the latter now uses the resolved
`radius_user` instead of `SubscriptionLabel`).

> **TODO**: confirm the `Reference` column name
> (`SUBSCRIPTION_REFERENCE_COLUMN` in `onebill_common.py`, currently
> `"Reference"`).

## 1. Setup

In [16]:
import sys, pathlib
sys.path.insert(0, str(pathlib.Path.cwd()))

from onebill_common import *  # noqa: F401,F403
from sqlalchemy import create_engine
from concurrent.futures import ThreadPoolExecutor

logger = get_logger("fetch_subscriptions")

# Use this to limit rows while testing. Set to None once ready for a full run.
TEST_ROW_LIMIT = None
BATCH_NUMBER =  os.environ["BATCH_NUMBER"]

## 2. Pull every subscription from MySQL

In [17]:
assert BI_DATASTORE_URL, "DB_USERNAME/DB_PASSWORD/DB_HOST not set in .env"
engine = create_engine(BI_DATASTORE_URL)

SUBSCRIPTION_QUERY = '''
SELECT 
    *
FROM bi_datastore.billing_subscription
WHERE _DataSource = 'vBill'
AND AccountCode = '99965692'
AND SubscriptionEndDate IS NULL;
'''.strip()

df_subscriptions = pd.read_sql(SUBSCRIPTION_QUERY, con=engine)
logger.info(f"Loaded {len(df_subscriptions):,} subscriptions from MySQL")

if TEST_ROW_LIMIT is not None:
    df_subscriptions = df_subscriptions.head(TEST_ROW_LIMIT)  # Testing limiter — remove/raise for a full run.
    logger.info(f"TEST_ROW_LIMIT active — trimmed to {len(df_subscriptions):,} rows")

df_subscriptions.head()

2026-07-27 10:11:06,824 [INFO] Loaded 264 subscriptions from MySQL

,_rowid,_rowmodified,_sourceid,_DataSource,AccountCode,ServiceType,SubscriptionUSN,SubscriptionLabel,SubscriptionStartDate,SubscriptionEndDate,...,CircuitType,Server,CustomerSuppliedReference,_notforreports_VoyagerOrderHistory,_notforreports_LegacyServiceDescription,NextPlanCode,NextPlanStartDate,NextQuantity,NextCustomPrice,SalesAgentCode
0,4163350815,2026-07-03 20:36:41,260726,vBill,99965692,Broadband - Fibre,V113061451,matthew.horncastle@williamsinternet.com,2025-11-26,None,...,UFB 1000/500/2.5/2.5,None,Williams Corporation,CPP 1006617,None,None,None,None,None,None
1,4167925657,2025-12-02 01:12:40,260841,vBill,99965692,Platforms,V113062335,V113062335,2025-12-01,None,...,None,None,None,CAS-973970-B7G2L8,None,None,None,None,None,None
2,4167926822,2025-12-02 01:12:40,260842,vBill,99965692,Platforms,V113062343,V113062343,2025-12-01,None,...,None,None,None,CAS-973970-B7G2L8,None,None,None,None,None,None
3,4167997507,2026-07-03 20:36:54,260846,vBill,99965692,Broadband - Fibre,V113062384,9matataway@williamsinternet.com,2025-12-01,None,...,UFB 100/20/2.5/2.5,None,WC CHCH T9,CPP 2006221,None,None,None,None,None,None
4,4167998688,2026-07-03 20:36:54,260847,vBill,99965692,Broadband - Fibre,V113062392,3matataway@williamsinternet.com,2025-12-01,None,...,UFB 100/20/2.5/2.5,None,WC CHCH T9,CPP 2006218,None,None,None,None,None,None

## 2b. Split active / inactive

Inactive subscriptions (`SubscriptionEndDate` already in the past) go
through a completely separate, much simpler pipeline —
`05_Fetch_Inactive_Subscriptions.ipynb` -> `06_Attach_Inactive_Addresses.ipynb`
-> `07_Create_Inactive_Subscription_Orders.ipynb` — no Voyager lookup at all
(the circuits endpoint doesn't return anything for a subscription that's
already ended), and no new address (they attach to the account's existing
default service address instead).

This notebook, from here on, only ever deals with ACTIVE subscriptions.
The inactive subset is saved to disk here so the inactive pipeline doesn't
need to re-run the same MySQL query.

In [18]:
_end_date = pd.to_datetime(df_subscriptions["SubscriptionEndDate"], errors="coerce")
_today = pd.Timestamp.now().normalize()
_is_active = _end_date.isna() | (_end_date >= _today)

df_subscriptions_inactive_raw = df_subscriptions[~_is_active].copy()
df_subscriptions = df_subscriptions[_is_active].copy()

logger.info(
    f"{len(df_subscriptions):,} active / {len(df_subscriptions_inactive_raw):,} inactive "
    f"(inactive = SubscriptionEndDate before {_today.date()})"
)

if not df_subscriptions_inactive_raw.empty:
    save_df("subscriptions_inactive_raw", df_subscriptions_inactive_raw)
    logger.info(
        f"Saved {len(df_subscriptions_inactive_raw):,} inactive subscriptions to "
        f"'subscriptions_inactive_raw' — pick these up in 05_Fetch_Inactive_Subscriptions.ipynb"
    )

2026-07-27 10:11:06,858 [INFO] 264 active / 0 inactive (inactive = SubscriptionEndDate before 2026-07-27)

## 3. Resolve target account for every subscription

`TargetAccountNumber` is now primarily the subscription's **own** account —
matched by `AccountCode` against `04_Create_Accounts.ipynb`'s real results
(`load_account_code_batch_map`), which is the actual OneBill `accountNumber`
(`AccountCode` + `.` + `BATCH_NUMBER`) for that account. This is what the
account is really called inside OneBill, so subscriptions land back on their
own account instead of one of the two shared Williams buckets.

If a subscription's own account has no successful (`created`/`exists`) row
in `account_results` — e.g. it wasn't migrated, or failed — it falls back to
the old two-bucket routing (`resolve_target_account`, based on `Reference`)
so the row can still be processed rather than being dropped outright.

Run `04_Create_Accounts.ipynb` before this notebook if you haven't already.

In [19]:
own_account_map = load_account_code_batch_map()  # {AccountCode: AccountCode_Batch}, every account in 04's results
real_account_numbers = load_real_target_account_numbers()  # {"managed_by_williams": "...", "williams_corporation": "..."}

missing_keys = set(TARGET_ACCOUNTS) - set(real_account_numbers)
if missing_keys:
    logger.warning(
        f"No successful account_results row found for: {missing_keys} — "
        f"falling back to the TARGET_ACCOUNTS placeholder for those. "
        f"Run 04_Create_Accounts.ipynb (or check it for failures) before trusting this run."
    )

logger.info(f"{len(own_account_map):,} accounts available from 04_Create_Accounts.ipynb (own-account routing)")

reference_col = SUBSCRIPTION_REFERENCE_COLUMN if SUBSCRIPTION_REFERENCE_COLUMN in df_subscriptions.columns else None
if reference_col is None:
    logger.warning(
        f"Column '{SUBSCRIPTION_REFERENCE_COLUMN}' not found in df_subscriptions — "
        f"Managed-by-Williams routing and the bucket fallback below can't work without it. "
        f"Available columns: {list(df_subscriptions.columns)}"
    )
    df_subscriptions["CustomerSuppliedReference"] = None
else:
    df_subscriptions["CustomerSuppliedReference"] = df_subscriptions[reference_col]

df_subscriptions["AccountCode"] = df_subscriptions["AccountCode"].astype(str)

# --- Business decision (2026-07-23): "Managed by Williams" subscriptions ALWAYS
# route to the shared bucket account, even when the subscription's own individual
# OneBill account already exists (created by 04_Create_Accounts.ipynb for every
# AccountCode). This takes priority over own-account routing below — it is
# checked first, not used as a fallback.
is_managed_by_williams = (
    df_subscriptions["CustomerSuppliedReference"].fillna("").astype(str).str.lower()
    .str.contains(MANAGED_BY_WILLIAMS_MARKER, regex=False)
)

managed_by_williams_number = real_account_numbers.get(
    "managed_by_williams", TARGET_ACCOUNTS["managed_by_williams"]["account_number"]
)
williams_corporation_number = real_account_numbers.get(
    "williams_corporation", TARGET_ACCOUNTS["williams_corporation"]["account_number"]
)

df_subscriptions["TargetAccountKey"] = None
df_subscriptions["TargetAccountNumber"] = None

# 1. Managed by Williams — always wins, regardless of own account.
df_subscriptions.loc[is_managed_by_williams, "TargetAccountKey"] = "managed_by_williams"
df_subscriptions.loc[is_managed_by_williams, "TargetAccountNumber"] = managed_by_williams_number
logger.info(
    f"{is_managed_by_williams.sum():,} subscriptions routed to the shared 'Managed by Williams' "
    f"account (Reference match — overrides own-account routing)"
)

# 2. Everyone else — own account first.
not_managed = ~is_managed_by_williams
df_subscriptions.loc[not_managed, "TargetAccountNumber"] = df_subscriptions.loc[not_managed, "AccountCode"].map(own_account_map)
df_subscriptions.loc[not_managed & df_subscriptions["TargetAccountNumber"].notna(), "TargetAccountKey"] = "own_account"

# 3. Everyone else, still without an account — Williams Corporation bucket fallback.
missing_own_account = not_managed & df_subscriptions["TargetAccountNumber"].isna()
if missing_own_account.any():
    logger.warning(
        f"{missing_own_account.sum():,} subscriptions have no matching created/existing account in "
        f"04_Create_Accounts.ipynb's results and aren't Managed-by-Williams — falling back to the "
        f"Williams Corporation bucket account for these."
    )
    df_subscriptions.loc[missing_own_account, "TargetAccountKey"] = "williams_corporation"
    df_subscriptions.loc[missing_own_account, "TargetAccountNumber"] = williams_corporation_number

logger.info(df_subscriptions["TargetAccountKey"].value_counts(dropna=False).to_string())
df_subscriptions[["SubscriptionUSN", "AccountCode", "CustomerSuppliedReference", "TargetAccountKey", "TargetAccountNumber"]].head(20)

2026-07-27 10:11:06,931 [WARNING] No successful account_results row found for: {'williams_corporation'} — falling back to the TARGET_ACCOUNTS placeholder for those. Run 04_Create_Accounts.ipynb (or check it for failures) before trusting this run.
2026-07-27 10:11:06,933 [INFO] 2 accounts available from 04_Create_Accounts.ipynb (own-account routing)

2026-07-27 10:11:06,942 [INFO] 133 subscriptions routed to the shared 'Managed by Williams' account (Reference match — overrides own-account routing)
2026-07-27 10:11:06,985 [INFO] TargetAccountKey
managed_by_williams    133
own_account            131

,SubscriptionUSN,AccountCode,CustomerSuppliedReference,TargetAccountKey,TargetAccountNumber
0,V113061451,99965692,Williams Corporation,own_account,99965692_fullbatch5
1,V113062335,99965692,None,own_account,99965692_fullbatch5
2,V113062343,99965692,None,own_account,99965692_fullbatch5
3,V113062384,99965692,WC CHCH T9,own_account,99965692_fullbatch5
4,V113062392,99965692,WC CHCH T9,own_account,99965692_fullbatch5
5,V113062400,99965692,WC CHCH T9,own_account,99965692_fullbatch5
6,V113062418,99965692,WC CHCH T9,own_account,99965692_fullbatch5
7,V113062632,99965692,WC CHCH T9,own_account,99965692_fullbatch5
8,V113062616,99965692,WC CHCH T9,own_account,99965692_fullbatch5
9,V113062962,99965692,WC CHCH T9,own_account,99965692_fullbatch5
10,V113062970,99965692,WC CHCH T9,own_account,99965692_fullbatch5
11,V113062988,99965692,WC CHCH T9,own_account,99965692_fullbatch5
12,V113062996,99965692,WC CHCH T9,own_account,99965692_fullbatch5
13,V113063002,99965692,WC CHCH T9,own_account,99965692_fullbatch5
14,V113063010,99965692,WC CHCH T9,own_account,99965692_fullbatch5
15,V113063036,99965692,WC CHCH T9,own_account,99965692_fullbatch5
16,V113063044,99965692,WC CHCH T9,own_account,99965692_fullbatch5
17,V113063051,99965692,WC CHCH T9,own_account,99965692_fullbatch5
18,V113063085,99965692,WC CHCH T9,own_account,99965692_fullbatch5
19,V113063168,99965692,WC CHCH T9,own_account,99965692_fullbatch5

## 4. Look up each subscription's real address + radius username (Voyager)

Two API calls per subscription, keyed on `SupplierServiceID`:
`fetch_voyager_circuit` -> `fetch_voyager_address`, wrapped by
`get_voyager_address`. Run in parallel (it's now real network calls, not
pure string parsing) via the same `ThreadPoolExecutor` pattern used in
`06_Create_Addresses.ipynb`.

Only ACTIVE subscriptions reach this point — inactive ones were split off
in step 2b and don't go through Voyager at all.

Subscriptions with no `SupplierServiceID`, or where either Voyager call
fails, come back with `parsed_ok = False` — flagged the same way unparsed
labels used to be, and skipped by `06_Create_Addresses.ipynb`.

In [20]:
if VOYAGER_CCP_KEY is None or VOYAGER_PARTNER_ID is None:
    logger.warning("VOYAGER_CCP_KEY / VOYAGER_PARTNER_ID not set — every Voyager lookup below will fail. Set them in .env.")

blank_supplier_ids = df_subscriptions["SupplierServiceID"].isna() | (df_subscriptions["SupplierServiceID"].astype(str).str.strip() == "")
if blank_supplier_ids.all():
    logger.warning(
        "SupplierServiceID is blank for EVERY subscription in this batch — the Voyager circuits lookup "
        "can't run at all without it, so every ParsedAddress_* field below will be None. Check the MySQL "
        "source data / SUBSCRIPTION_QUERY in step 2 before re-running."
    )
elif blank_supplier_ids.any():
    logger.warning(f"{blank_supplier_ids.sum():,} / {len(df_subscriptions):,} subscriptions have a blank SupplierServiceID")

voyager_session = new_voyager_session(max_workers=MAX_WORKERS)


def _lookup_row(supplier_service_id):
    return get_voyager_address(voyager_session, supplier_service_id)


logger.info(f"Looking up Voyager address for {len(df_subscriptions):,} subscriptions with {MAX_WORKERS} workers...")

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    voyager_results = list(executor.map(_lookup_row, df_subscriptions["SupplierServiceID"]))

existing_parsed_cols = [c for c in df_subscriptions.columns if c.startswith("ParsedAddress_")]
if existing_parsed_cols:
    df_subscriptions = df_subscriptions.drop(columns=existing_parsed_cols)  # safe to re-run this cell

address_parts = pd.DataFrame(voyager_results, index=df_subscriptions.index)
address_parts = address_parts.add_prefix("ParsedAddress_")
df_subscriptions = pd.concat([df_subscriptions, address_parts], axis=1)

unparsed = df_subscriptions[~df_subscriptions["ParsedAddress_parsed_ok"]]
if not unparsed.empty:
    logger.warning(f"{len(unparsed):,} subscriptions could not be resolved to a Voyager address")
    error_summary = (
        unparsed["ParsedAddress_error"].value_counts(dropna=False)
        .rename_axis("error").reset_index(name="count")
    )
    logger.info("Error breakdown:\n" + error_summary.to_string(index=False))

df_subscriptions[[
    "SubscriptionLabel", "SupplierServiceID",
    "ParsedAddress_addLine1", "ParsedAddress_addLine2", "ParsedAddress_city",
    "ParsedAddress_postcode", "ParsedAddress_region_iso", "ParsedAddress_region_code_raw", "ParsedAddress_radius_user",
    "ParsedAddress_parsed_ok", "ParsedAddress_error",
]].head(20)

2026-07-27 10:11:07,031 [WARNING] 3 / 264 subscriptions have a blank SupplierServiceID
2026-07-27 10:11:07,059 [INFO] Looking up Voyager address for 264 subscriptions with 10 workers...
2026-07-27 10:11:49,596 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/f2be7a4bae3af3a8f1810836416e4ca3062be72a — retry 1/6 in 29.4s
2026-07-27 10:11:50,159 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180358 — retry 1/3 in 2.4s
2026-07-27 10:11:50,596 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/1f5b0d33d3fc6478cf7a1c2c910fd831c56d69fa — retry 1/6 in 28.0s
2026-07-27 10:11:51,153 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180367 — retry 1/3 in 2.5s
2026-07-27 10:11:51,586 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/d6c4334b30065884470b1a4806a4f0a569702014 — retry 1/6 in 27.4s
2026-07-27 10:11:52,087 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/c3728eacaa253b248a68e5b93456db58001190b1 — retry 1/6 in 27.3s
2026-07-27 10:11:52,600 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/7db63cf0bc637a42d86184bc4111f11d6e5a3913 — retry 1/6 in 26.3s
2026-07-27 10:11:53,096 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/0b031f58df001b3ee5dfcc12ecccaeecea873916 — retry 1/6 in 26.3s
2026-07-27 10:11:53,589 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/30e6a8894242ce29c1d3432fc02c90a3bf6c7ba1 — retry 1/6 in 25.2s
2026-07-27 10:11:54,099 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/321d929e7257192fc3a26e453343876eaff97d3e — retry 1/6 in 25.4s
2026-07-27 10:11:54,670 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180358 — retry 2/3 in 4.1s
2026-07-27 10:11:55,159 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180367 — retry 2/3 in 4.3s
2026-07-27 10:11:59,301 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180358 — retry 3/3 in 8.4s
2026-07-27 10:11:59,983 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180367 — retry 3/3 in 8.4s
2026-07-27 10:12:08,785 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180637 — retry 1/3 in 2.4s
2026-07-27 10:12:09,853 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180230 — retry 1/3 in 2.1s
2026-07-27 10:12:11,775 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180637 — retry 2/3 in 4.1s
2026-07-27 10:12:12,496 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180230 — retry 2/3 in 4.4s
2026-07-27 10:12:16,466 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180637 — retry 3/3 in 8.3s
2026-07-27 10:12:17,454 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643180230 — retry 3/3 in 8.4s
2026-07-27 10:12:51,178 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/e128e8a4ec0990679b6fa53833055322765dd0c7 — retry 1/6 in 28.2s
2026-07-27 10:12:51,682 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/ea026618d2a9a5e9dbb3175ea1e42d057faee311 — retry 1/6 in 28.5s
2026-07-27 10:12:52,184 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/3e648e0c986dd68ec8e10c3e2f3818b1748cfd98 — retry 1/6 in 27.5s
2026-07-27 10:12:52,738 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02622115 — retry 1/3 in 2.5s
2026-07-27 10:12:54,179 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/86c588998e5b8953f939760424352afff2324f75 — retry 1/6 in 25.2s
2026-07-27 10:12:55,188 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/bcd88c0b9acad4a4b6247ccd4b0cecc62424a030 — retry 1/6 in 24.0s
2026-07-27 10:12:55,712 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/52766c081c2f899b37dffe15fe90a4db3e3db28b — retry 1/6 in 24.1s
2026-07-27 10:12:56,191 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/4d1329781a68b3176469d288ae22153e4b5067f9 — retry 1/6 in 23.3s
2026-07-27 10:12:56,681 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/7be6f4257facecb230b3c63cc2794b50d6a7b1bb — retry 1/6 in 23.2s
2026-07-27 10:12:57,200 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/3e04663ae3a601669d1c76eeb06da64b09775b04 — retry 1/6 in 22.0s
2026-07-27 10:12:57,772 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02622115 — retry 2/3 in 4.4s
2026-07-27 10:13:02,701 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02622115 — retry 3/3 in 8.4s
2026-07-27 10:13:13,123 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/a1ec70edff5ddc0f775c708799b7f98304d7ba60 — retry 1/6 in 7.1s
2026-07-27 10:13:50,211 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/4f6544a2036f6a0d9e5c860a2caabe40a726a187 — retry 1/6 in 29.3s
2026-07-27 10:13:50,711 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/f7160bbebcc6dad8d40b646af7c6ad9cee41057a — retry 1/6 in 29.3s
2026-07-27 10:13:51,209 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/059831e1da3d2255ba92756473324aa6aff8b9ad — retry 1/6 in 28.4s
2026-07-27 10:13:51,715 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/481382b16bbf61fbad3c2c2aac7ec286be10c435 — retry 1/6 in 28.3s
2026-07-27 10:13:52,250 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/ed315a5f9e932c4617486440ded37218088561be — retry 1/6 in 27.4s
2026-07-27 10:13:52,780 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02626248 — retry 1/3 in 2.3s
2026-07-27 10:13:53,209 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/7929764f85decd68d3a06f869434165dfa85314e — retry 1/6 in 26.2s
2026-07-27 10:13:53,713 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/405c210e9ff0e48c489377e9d372bf9a33cc2f72 — retry 1/6 in 26.2s
2026-07-27 10:13:54,246 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/bcd88c0b9acad4a4b6247ccd4b0cecc62424a030 — retry 1/6 in 25.4s
2026-07-27 10:13:54,776 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02626213 — retry 1/3 in 2.1s
2026-07-27 10:13:55,618 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02626248 — retry 2/3 in 4.1s
2026-07-27 10:13:57,419 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02626213 — retry 2/3 in 4.2s
2026-07-27 10:14:00,240 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02626248 — retry 3/3 in 8.4s
2026-07-27 10:14:02,160 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02626213 — retry 3/3 in 8.2s
2026-07-27 10:14:09,793 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02626854 — retry 1/3 in 2.3s
2026-07-27 10:14:11,410 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643227643 — retry 1/3 in 2.3s
2026-07-27 10:14:12,606 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02626854 — retry 2/3 in 4.4s
2026-07-27 10:14:14,360 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643227643 — retry 2/3 in 4.2s
2026-07-27 10:14:17,580 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02626854 — retry 3/3 in 8.1s
2026-07-27 10:14:19,067 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643227643 — retry 3/3 in 8.4s
2026-07-27 10:14:50,102 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630674 — retry 1/3 in 2.2s
2026-07-27 10:14:50,539 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/6dc422985392dad55e72d090cc91bdf9c4c10f8a — retry 1/6 in 29.5s
2026-07-27 10:14:51,047 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/13d4e909be3b32b4f66fd9d613033f8e54be096c — retry 1/6 in 29.3s
2026-07-27 10:14:51,590 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630679 — retry 1/3 in 2.4s
2026-07-27 10:14:52,096 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630627 — retry 1/3 in 2.5s
2026-07-27 10:14:52,516 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/43f7bcc7949629ba5cc32dde163f9c2d0f4fc441 — retry 1/6 in 27.4s
2026-07-27 10:14:53,010 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/4afc6e52a6d6558aa676dfa1711db9794fc7db78 — retry 1/6 in 27.1s
2026-07-27 10:14:53,531 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/0bec28f5d46509574538457262ca47bf3502cee6 — retry 1/6 in 26.4s
2026-07-27 10:14:54,085 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630623 — retry 1/3 in 2.2s
2026-07-27 10:14:54,587 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630677 — retry 1/3 in 2.2s
2026-07-27 10:14:55,067 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630674 — retry 2/3 in 4.1s
2026-07-27 10:14:55,572 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630679 — retry 2/3 in 4.3s
2026-07-27 10:14:56,105 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630627 — retry 2/3 in 4.2s
2026-07-27 10:14:56,866 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630623 — retry 2/3 in 4.4s
2026-07-27 10:14:57,349 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630677 — retry 2/3 in 4.3s
2026-07-27 10:14:59,771 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630674 — retry 3/3 in 8.5s
2026-07-27 10:15:00,391 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630679 — retry 3/3 in 8.5s
2026-07-27 10:15:00,878 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630627 — retry 3/3 in 8.5s
2026-07-27 10:15:01,850 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630623 — retry 3/3 in 8.1s
2026-07-27 10:15:02,350 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630677 — retry 3/3 in 8.5s
2026-07-27 10:15:10,331 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/1bdbf49e9075e14eda4149e78becef401c4db569 — retry 1/6 in 9.4s
2026-07-27 10:15:11,439 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643250002 — retry 1/3 in 2.3s
2026-07-27 10:15:12,842 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643250015 — retry 1/3 in 2.4s
2026-07-27 10:15:13,855 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02631124 — retry 1/3 in 2.0s
2026-07-27 10:15:14,405 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630675 — retry 1/3 in 2.4s
2026-07-27 10:15:14,849 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643250002 — retry 2/3 in 4.4s
2026-07-27 10:15:15,820 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643250015 — retry 2/3 in 4.3s
2026-07-27 10:15:16,468 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02631124 — retry 2/3 in 4.1s
2026-07-27 10:15:17,322 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02630675 — retry 2/3 in 4.4s
2026-07-27 10:15:50,269 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/f12b791e8cf2b1bb95a817bc176a656b9cdd02e8 — retry 1/6 in 29.4s
2026-07-27 10:15:50,779 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/6bb18e4558a21e96cc530305d8747d686e1fcc9a — retry 1/6 in 29.3s
2026-07-27 10:15:51,266 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/d5b53df5eb43c1ba7696cd2901d230010d40dce2 — retry 1/6 in 28.0s
2026-07-27 10:15:51,769 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/7a23bb5565705615fafdd36f2e8d7ce7b9f9d545 — retry 1/6 in 28.2s
2026-07-27 10:15:52,278 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/ee474a8866f6687dec75fd123fd08e28950f41f5 — retry 1/6 in 27.4s
2026-07-27 10:15:52,815 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02635937 — retry 1/3 in 2.2s
2026-07-27 10:15:53,339 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636015 — retry 1/3 in 2.2s
2026-07-27 10:15:53,841 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636011 — retry 1/3 in 2.3s
2026-07-27 10:15:54,390 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636005 — retry 1/3 in 2.4s
2026-07-27 10:15:54,789 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/1eddbe8dac5d7df14c9e9c2c3e6f2a747441f22a — retry 1/6 in 25.0s
2026-07-27 10:15:55,572 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02635937 — retry 2/3 in 4.3s
2026-07-27 10:15:56,132 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636015 — retry 2/3 in 4.5s
2026-07-27 10:15:56,744 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636011 — retry 2/3 in 4.4s
2026-07-27 10:15:57,280 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636005 — retry 2/3 in 4.2s
2026-07-27 10:16:00,424 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02635937 — retry 3/3 in 8.5s
2026-07-27 10:16:01,238 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636015 — retry 3/3 in 8.2s
2026-07-27 10:16:01,762 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636011 — retry 3/3 in 8.2s
2026-07-27 10:16:02,228 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636005 — retry 3/3 in 8.3s
2026-07-27 10:16:10,003 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636007 — retry 1/3 in 2.4s
2026-07-27 10:16:11,472 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636003 — retry 1/3 in 2.1s
2026-07-27 10:16:12,508 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636017 — retry 1/3 in 2.2s
2026-07-27 10:16:12,989 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636002 — retry 1/3 in 2.1s
2026-07-27 10:16:13,474 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636007 — retry 2/3 in 4.4s
2026-07-27 10:16:14,109 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636003 — retry 2/3 in 4.2s
2026-07-27 10:16:15,252 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636017 — retry 2/3 in 4.4s
2026-07-27 10:16:15,744 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636002 — retry 2/3 in 4.3s
2026-07-27 10:16:18,433 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636007 — retry 3/3 in 8.1s
2026-07-27 10:16:18,958 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02636003 — retry 3/3 in 8.0s
2026-07-27 10:16:49,838 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/401936aa8e5ca248420363a5e30629ec900aa4fa — retry 1/6 in 30.2s
2026-07-27 10:16:50,449 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02637125 — retry 1/3 in 2.4s
2026-07-27 10:16:50,897 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02635058 — retry 1/3 in 2.4s
2026-07-27 10:16:51,350 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/7f0d00ba9cdecc902b7cdadfca6761d060bcd851 — retry 1/6 in 28.3s
2026-07-27 10:16:51,885 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02638281 — retry 1/3 in 2.2s
2026-07-27 10:16:52,410 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02638282 — retry 1/3 in 2.3s
2026-07-27 10:16:52,848 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/87147a84ca310662fa1e8aaa50ab344dc37d0d89 — retry 1/6 in 27.1s
2026-07-27 10:16:53,312 [WARNING] Voyager 429 on https://api.voyager.nz/address-search/v3/addresses/id/3b66fc53d360061d9a48c74184ef9d1100b388c9 — retry 1/6 in 26.0s
2026-07-27 10:16:53,913 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02638363 — retry 1/3 in 2.4s
2026-07-27 10:16:54,375 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306020 — retry 1/3 in 2.0s
2026-07-27 10:16:54,873 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02637125 — retry 2/3 in 4.3s
2026-07-27 10:16:55,394 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02635058 — retry 2/3 in 4.2s
2026-07-27 10:16:55,882 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02638281 — retry 2/3 in 4.1s
2026-07-27 10:16:56,383 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02638282 — retry 2/3 in 4.3s
2026-07-27 10:16:56,862 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02638363 — retry 2/3 in 4.1s
2026-07-27 10:16:57,380 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306020 — retry 2/3 in 4.5s
2026-07-27 10:16:59,729 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02637125 — retry 3/3 in 8.4s
2026-07-27 10:17:00,215 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02635058 — retry 3/3 in 8.3s
2026-07-27 10:17:00,725 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02638281 — retry 3/3 in 8.4s
2026-07-27 10:17:01,693 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02638282 — retry 3/3 in 8.5s
2026-07-27 10:17:01,952 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02638363 — retry 3/3 in 8.4s
2026-07-27 10:17:02,376 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306020 — retry 3/3 in 8.3s
2026-07-27 10:17:09,667 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306031 — retry 1/3 in 2.1s
2026-07-27 10:17:10,140 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306037 — retry 1/3 in 2.4s
2026-07-27 10:17:12,663 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306050 — retry 1/3 in 2.2s
2026-07-27 10:17:13,306 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306233 — retry 1/3 in 2.0s
2026-07-27 10:17:13,667 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306244 — retry 1/3 in 2.3s
2026-07-27 10:17:14,179 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306031 — retry 2/3 in 4.2s
2026-07-27 10:17:14,682 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02639541 — retry 1/3 in 2.2s
2026-07-27 10:17:15,170 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306037 — retry 2/3 in 4.2s
2026-07-27 10:17:15,693 [WARNING] Voyager 500 on https://api.voyager.nz/fibre/v1/circuits/1643306050 — retry 2/3 in 4.3s
2026-07-27 10:17:15,951 [WARNING] Voyager 429 on https://api.voyager.nz/fibre/v1/circuits/1643306233 — retry 1/6 in 60.2s
2026-07-27 10:17:16,478 [WARNING] Voyager 429 on https://api.voyager.nz/fibre/v1/circuits/1643306244 — retry 1/6 in 59.5s
2026-07-27 10:17:17,269 [WARNING] Voyager 429 on https://api.voyager.nz/fibre/v1/circuits/ENVOYB02639541 — retry 1/6 in 58.1s
2026-07-27 10:17:18,726 [WARNING] Voyager 429 on https://api.voyager.nz/fibre/v1/circuits/1643306031 — retry 1/6 in 57.1s
2026-07-27 10:17:20,205 [WARNING] Voyager 429 on https://api.voyager.nz/fibre/v1/circuits/1643306037 — retry 1/6 in 55.5s

,SubscriptionLabel,SupplierServiceID,ParsedAddress_addLine1,ParsedAddress_addLine2,ParsedAddress_city,ParsedAddress_postcode,ParsedAddress_region_iso,ParsedAddress_region_code_raw,ParsedAddress_radius_user,ParsedAddress_parsed_ok,ParsedAddress_error
0,matthew.horncastle@williamsinternet.com,ENVOYB02618143,39 Chester Street West,Christchurch Central,Christchurch,8013,CAN,CAN,matthew.horncastle@williamsinternet.com,True,None
1,V113062335,None,None,None,None,None,None,None,None,False,no SupplierServiceID on this subscription
2,V113062343,None,None,None,None,None,None,None,None,False,no SupplierServiceID on this subscription
3,9matataway@williamsinternet.com,UFF000007009674,9 Matata Way,Tauranga,Tauranga,3110,BOP,BOP,9matataway@williamsinternet.com,True,None
4,3matataway@williamsinternet.com,UFF000007009635,3 Matata Way,Tauranga,Tauranga,3110,BOP,BOP,3matataway@williamsinternet.com,True,None
5,5matataway@williamsinternet.com,UFF000007009642,None,None,None,None,None,None,None,False,circuits lookup failed: HTTPSConnectionPool(ho...
6,11matataway@williamsinternet.com,UFF000007009690,None,None,None,None,None,None,None,False,circuits lookup failed: HTTPSConnectionPool(ho...
7,7.13biddle@williamsinternet.com,1643175950,None,None,None,None,None,None,None,False,circuits lookup failed: HTTPSConnectionPool(ho...
8,7matataway@williamsinternet.com,UFF000007009661,None,None,None,None,None,None,None,False,circuits lookup failed: HTTPSConnectionPool(ho...
9,1810fathom@williamsinternet.com,1643175154,None,None,None,None,None,None,None,False,circuits lookup failed: HTTPSConnectionPool(ho...
10,3.21awaroa@williamsinternet.com,1643175163,None,None,None,None,None,None,None,False,circuits lookup failed: HTTPSConnectionPool(ho...
11,3.23awaroa@williamsinternet.com,1643175168,None,None,None,None,None,None,None,False,circuits lookup failed: HTTPSConnectionPool(ho...
12,1643175171@no-username,1643175171,3302/51 Albert Street,Auckland Central,Auckland,1010,AUK,AUK,3302.51albert@williamsinternet.com,True,None
13,5.21awaroa@williamsinternet.com,1643175175,5/21 Awaroa Road,Sunnyvale,Waitakere,0612,AUK,AUK,5.21awaroa@williamsinternet.com,True,None
14,1643175178@no-username,1643175178,5/23 Awaroa Road,Sunnyvale,Waitakere,0612,AUK,AUK,5.23awaroa@williamsinternet.com,True,None
15,19.10fathom@williamsinternet.com,1643175252,19/10 Fathom Place,Te Atatu Peninsula,Waitakere,0610,AUK,AUK,19.10fathom@williamsinternet.com,True,None
16,1.4johnston@williamsinternet.com,1643175711,1/4 Johnston Grove,Taita,Lower Hutt,5011,WGN,WGN,1.4johnston@williamsinternet.com,True,None
17,10.0liver@williamsinternet.com,1643175754,10 Oliver Place,Trentham,Upper Hutt,5018,WGN,WGN,10.0liver@williamsinternet.com,True,None
18,11.oliver@williamsinternet.com,1643175805,11 Oliver Place,Trentham,Upper Hutt,5018,WGN,WGN,11.oliver@williamsinternet.com,True,None
19,2.5ariki@williamsinternet.com,1643175885,2/5 Ariki Street,Boulcott,Lower Hutt,5010,WGN,WGN,2.5ariki@williamsinternet.com,True,None

In [21]:
# Second pass: retry subscriptions that failed with a transient 5xx on the
# first pass, after a longer cooldown. 404s / "no SupplierServiceID" are
# permanent and intentionally skipped -- see voyager_second_pass() docstring.
SECOND_PASS_DELAY_SECONDS = 90  # bump this up if the same circuits still fail after 90s

df_subscriptions = voyager_second_pass(
    df_subscriptions,
    voyager_session,
    delay_seconds=SECOND_PASS_DELAY_SECONDS,
    max_workers=MAX_WORKERS,
)

unparsed = df_subscriptions[~df_subscriptions["ParsedAddress_parsed_ok"]]
if not unparsed.empty:
    error_summary = (
        unparsed["ParsedAddress_error"].value_counts(dropna=False)
        .rename_axis("error").reset_index(name="count")
    )
    logger.info(f"{len(unparsed):,} subscriptions still unresolved overall:\n" + error_summary.to_string(index=False))
else:
    logger.info("All subscriptions resolved.")

unparsed[["SubscriptionUSN", "SupplierServiceID", "ParsedAddress_error"]]

2026-07-27 10:19:26,038 [INFO] Voyager second pass: 24 subscriptions failed with a transient 5xx on the first pass — waiting 90s before retrying...
2026-07-27 10:21:19,576 [INFO] Voyager second pass: 23 / 24 resolved on retry.
2026-07-27 10:21:19,581 [INFO] 17 subscriptions still unresolved after second pass:
                                                                                                                                                                                                                                                                          error  count
                                                                                                                                                                                                                                      no SupplierServiceID on this subscription      3
                                                                                                                                                           circuits lookup failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))      2
circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/UFF000007009690 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
     circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/1643175950 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/UFF000007009661 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/UFF000007009642 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
     circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/1643175154 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
     circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/1643175163 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
     circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/1643175168 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
                                                                                                                                                           circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/ENVOYB02622491      1
                                                                                                                                                           circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/ENVOYB02624632      1
                                                                                                                                                           circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/ENVOYB02627005      1
                                                                                                                                                               circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/1643259206      1
                                                                                                                                                           circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/ENVOYB02633693      1
2026-07-27 10:21:19,587 [INFO] 17 subscriptions still unresolved overall:
                                                                                                                                                                                                                                                                          error  count
                                                                                                                                                                                                                                      no SupplierServiceID on this subscription      3
                                                                                                                                                           circuits lookup failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))      2
circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/UFF000007009690 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
     circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/1643175950 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/UFF000007009661 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/UFF000007009642 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
     circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/1643175154 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
     circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/1643175163 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
     circuits lookup failed: HTTPSConnectionPool(host='api.voyager.nz', port=443): Max retries exceeded with url: /fibre/v1/circuits/1643175168 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))      1
                                                                                                                                                           circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/ENVOYB02622491      1
                                                                                                                                                           circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/ENVOYB02624632      1
                                                                                                                                                           circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/ENVOYB02627005      1
                                                                                                                                                               circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/1643259206      1
                                                                                                                                                           circuits lookup failed: 404 Client Error: Not Found for url: https://api.voyager.nz/fibre/v1/circuits/ENVOYB02633693      1

,SubscriptionUSN,SupplierServiceID,ParsedAddress_error
1,V113062335,None,no SupplierServiceID on this subscription
2,V113062343,None,no SupplierServiceID on this subscription
5,V113062400,UFF000007009642,circuits lookup failed: HTTPSConnectionPool(ho...
6,V113062418,UFF000007009690,circuits lookup failed: HTTPSConnectionPool(ho...
7,V113062632,1643175950,circuits lookup failed: HTTPSConnectionPool(ho...
8,V113062616,UFF000007009661,circuits lookup failed: HTTPSConnectionPool(ho...
9,V113062962,1643175154,circuits lookup failed: HTTPSConnectionPool(ho...
10,V113062970,1643175163,circuits lookup failed: HTTPSConnectionPool(ho...
11,V113062988,1643175168,circuits lookup failed: HTTPSConnectionPool(ho...
43,V113064133,1643180358,circuits lookup failed: ('Connection aborted.'...
80,V113066765,ENVOYB02622491,circuits lookup failed: 404 Client Error: Not ...
91,V113068670,ENVOYB02624632,circuits lookup failed: 404 Client Error: Not ...
117,V113071120,ENVOYB02627005,circuits lookup failed: 404 Client Error: Not ...
126,V113071849,None,no SupplierServiceID on this subscription
152,V113074579,1643259206,circuits lookup failed: 404 Client Error: Not ...
160,V113076806,ENVOYB02633693,circuits lookup failed: 404 Client Error: Not ...
261,V113088512,1643342820,circuits lookup failed: ('Connection aborted.'...

In [22]:
df_subscriptions["SupplierServiceID"] = df_subscriptions["SupplierServiceID"] + BATCH_NUMBER
df_subscriptions["ParsedAddress_radius_user	"] = df_subscriptions["ParsedAddress_radius_user"] + BATCH_NUMBER
df_subscriptions.head()

,_rowid,_rowmodified,_sourceid,_DataSource,AccountCode,ServiceType,SubscriptionUSN,SubscriptionLabel,SubscriptionStartDate,SubscriptionEndDate,...,ParsedAddress_city,ParsedAddress_postcode,ParsedAddress_region_name,ParsedAddress_region_iso,ParsedAddress_region_code_raw,ParsedAddress_radius_user,ParsedAddress_location_id,ParsedAddress_parsed_ok,ParsedAddress_error,ParsedAddress_radius_user\t
0,4163350815,2026-07-03 20:36:41,260726,vBill,99965692,Broadband - Fibre,V113061451,matthew.horncastle@williamsinternet.com,2025-11-26,None,...,Christchurch,8013,CANTERBURY REGION,CAN,CAN,matthew.horncastle@williamsinternet.com,36049ea46dd36a68eba30fd8cd7f6012a7d7e650,True,None,matthew.horncastle@williamsinternet.com_fullba...
1,4167925657,2025-12-02 01:12:40,260841,vBill,99965692,Platforms,V113062335,V113062335,2025-12-01,None,...,None,None,None,None,None,None,None,False,no SupplierServiceID on this subscription,NaN
2,4167926822,2025-12-02 01:12:40,260842,vBill,99965692,Platforms,V113062343,V113062343,2025-12-01,None,...,None,None,None,None,None,None,None,False,no SupplierServiceID on this subscription,NaN
3,4167997507,2026-07-03 20:36:54,260846,vBill,99965692,Broadband - Fibre,V113062384,9matataway@williamsinternet.com,2025-12-01,None,...,Tauranga,3110,BAY OF PLENTY REGION,BOP,BOP,9matataway@williamsinternet.com,44d46826807ccd9435dd3bc7070281ba2afb4cb2,True,None,9matataway@williamsinternet.com_fullbatch5
4,4167998688,2026-07-03 20:36:54,260847,vBill,99965692,Broadband - Fibre,V113062392,3matataway@williamsinternet.com,2025-12-01,None,...,Tauranga,3110,BAY OF PLENTY REGION,BOP,BOP,3matataway@williamsinternet.com,9160e43272e2e61bc9c00f45651914d21dab5a84,True,None,3matataway@williamsinternet.com_fullbatch5

## 5. Save

In [23]:
save_df("subscriptions_resolved", df_subscriptions)

Saved 264 rows -> migration_data\05_subscriptions_resolved.csv