# 07 — Create Subscription Orders (active)

The final creation step for ACTIVE subscriptions — the ones that went through
the full Voyager address lookup. For inactive subscriptions, see
`07_Create_Inactive_Subscription_Orders.ipynb`.

`build_subscription_order_payload`, `create_order_for_subscription`, and
`create_all_orders` now live in `onebill_common.py`, shared with the inactive
notebook — this notebook just loads the active-pipeline data and calls them.

For every subscription that got an address in `06_Create_Addresses.ipynb`:

1. Resolve its plan — `03_Match_Plan_Codes.ipynb` mapping, falling back to
   `STATIC_FALLBACK_PLAN` if unmatched.
2. Optionally attach a primary-contact summary from
   `01_Fetch_Contacts.ipynb` (see `ATTACH_CONTACT_SUMMARY_TO_ORDER`).
3. Build the order payload per the field mapping below.
4. `POST /rest/OrderService/v1/order`.

**vBill -> OneBill field mapping**

| OneBill field | Source |
|---|---|
| Subscription Username | vBill Subscription Label |
| External Service ID | Supplier Service ID |
| Imported Subscription USN | Subscription USN |
| Subscription USN | *(autogenerated by OneBill — not sent)* |
| Radius Username | Voyager `radiusUsers[0]` (from `05_Fetch_Subscriptions.ipynb`'s circuits lookup), falling back to vBill Subscription Label if Voyager didn't return one |
| Activation date | Subscription Start Date |
| Recurring-from date | fixed `2026-08-01` |
| Term | `0` if `SubscriptionEndDate` and `NextPlanStartDate` are both null, else `1` |
| followOnTermDetails.term | (only when Term=1) whole months between today and `SubscriptionEndDate` (falling back to `NextPlanStartDate` if the end date is null) |
| Vendor | `Supplier` mapped via `SUPPLIER_TO_VENDOR` (Chorus/Enable/UFF -> chorus/enable/tff); omitted + logged if `Supplier` is set but unmapped |

> **NOTE**: `resolve_vendor()` reads `subscription["Supplier"]` — this notebook pulls `df_subscriptions` via `SELECT *` from `bi_datastore.billing_subscription`, so double-check that's the exact column name in your MySQL table (vs. e.g. `SupplierName`) before a full run; if it's different, update the `.get("Supplier")` calls in `build_subscription_order_payload`.

## 1. Setup — load everything the previous notebooks produced

In [9]:
import sys, pathlib
sys.path.insert(0, str(pathlib.Path.cwd()))

from onebill_common import *  # noqa: F401,F403
from concurrent.futures import ThreadPoolExecutor, as_completed

logger = get_logger("create_subscription_orders")

df_subscriptions   = load_subscriptions_resolved()
df_address_results = load_df("address_results", dtype={"ship_add_id": str})
df_plan_mapping     = try_load_df("plan_mapping", dtype=str)
df_contacts          = try_load_df("contacts")

if df_plan_mapping is None:
    logger.warning("03_plan_code_mapping.csv not found — every subscription falls back to STATIC_FALLBACK_PLAN.")
    df_plan_mapping = pd.DataFrame(columns=["PlanCode", "product_name", "priceplan_name"])

if df_contacts is None and ATTACH_CONTACT_SUMMARY_TO_ORDER:
    logger.warning("01_contacts_by_account.csv not found — orders will be created without a contact summary.")

logger.info(
    f"{len(df_subscriptions):,} subscriptions, {len(df_address_results):,} address results, "
    f"{len(df_plan_mapping):,} plan mappings, "
    f"{len(df_contacts) if df_contacts is not None else 0:,} contact summaries"
)

2026-07-27 11:06:00,565 [INFO] 264 subscriptions, 264 address results, 9 plan mappings, 37,552 contact summaries

## 2. Join subscriptions with their address result

In [10]:
df_work = df_subscriptions.merge(
    df_address_results[["SubscriptionUSN", "status", "ship_add_id", "error"]].rename(
        columns={"status": "AddressStatus", "error": "AddressError"}
    ),
    on="SubscriptionUSN", how="left",
)

ready = df_work[df_work["AddressStatus"].isin(["created", "exists"])]
not_ready = df_work[~df_work["AddressStatus"].isin(["created", "exists"])]
logger.info(f"{len(ready):,} subscriptions have an address and are ready for order creation; "
            f"{len(not_ready):,} do not and will be skipped")
not_ready[["SubscriptionUSN", "AddressStatus", "AddressError"]].head(20)

2026-07-27 11:06:00,711 [INFO] 247 subscriptions have an address and are ready for order creation; 17 do not and will be skipped

,SubscriptionUSN,AddressStatus,AddressError
1,V113062335,skipped,no SupplierServiceID on this subscription
2,V113062343,skipped,no SupplierServiceID on this subscription
5,V113062400,skipped,circuits lookup failed: HTTPSConnectionPool(ho...
6,V113062418,skipped,circuits lookup failed: HTTPSConnectionPool(ho...
7,V113062632,skipped,circuits lookup failed: HTTPSConnectionPool(ho...
8,V113062616,skipped,circuits lookup failed: HTTPSConnectionPool(ho...
9,V113062962,skipped,circuits lookup failed: HTTPSConnectionPool(ho...
10,V113062970,skipped,circuits lookup failed: HTTPSConnectionPool(ho...
11,V113062988,skipped,circuits lookup failed: HTTPSConnectionPool(ho...
43,V113064133,skipped,circuits lookup failed: ('Connection aborted.'...
80,V113066765,skipped,circuits lookup failed: 404 Client Error: Not ...
91,V113068670,skipped,circuits lookup failed: 404 Client Error: Not ...
117,V113071120,skipped,circuits lookup failed: 404 Client Error: Not ...
126,V113071849,skipped,no SupplierServiceID on this subscription
152,V113074579,skipped,circuits lookup failed: 404 Client Error: Not ...
160,V113076806,skipped,circuits lookup failed: 404 Client Error: Not ...
261,V113088512,skipped,circuits lookup failed: ('Connection aborted.'...

## 3. Plan resolution

In [11]:
resolve_plan = make_plan_resolver(df_plan_mapping)

## 4. Contact-summary lookup (optional)

Joins each subscription's *original* vBill `AccountCode` (not the bucket
account) against `01_Fetch_Contacts.ipynb`'s output.

In [12]:
contact_summary_attributes = make_contact_summary_fn(df_contacts)

## 5. Build the order payload (field mapping)

In [13]:
# build_subscription_order_payload is now defined in onebill_common.py (shared with
# 07_Create_Inactive_Subscription_Orders.ipynb) — nothing to define here.

## 6. Per-subscription worker

In [14]:
# create_order_for_subscription is now defined in onebill_common.py (shared with
# 07_Create_Inactive_Subscription_Orders.ipynb) — nothing to define here.

## 7. Run (parallel driver)

In [15]:
order_results_df = create_all_orders(ready, resolve_plan, contact_summary_attributes)
order_results_df.head(20)

2026-07-27 11:06:04,062 [INFO] Creating orders for 247 subscriptions with 10 workers...

2026-07-27 11:06:25,960 [INFO] [OK] subscription V113062392 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:27,168 [INFO] [OK] subscription V113063044 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:28,346 [INFO] [OK] subscription V113063085 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:29,784 [INFO] [OK] subscription V113063036 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:31,043 [INFO] [OK] subscription V113062996 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:32,183 [INFO] [OK] subscription V113061451 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:33,366 [INFO] [OK] subscription V113062384 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:34,609 [INFO] [OK] subscription V113063002 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:35,953 [INFO] [OK] subscription V113063051 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:37,221 [INFO] [OK] subscription V113063010 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:38,365 [INFO] [OK] subscription V113063168 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:39,520 [INFO] [OK] subscription V113063176 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:40,804 [INFO] [OK] subscription V113063200 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:41,946 [INFO] [OK] subscription V113063218 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:43,097 [INFO] [OK] subscription V113063028 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:44,359 [INFO] [OK] subscription V113063069 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:45,492 [INFO] [OK] subscription V113063093 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:46,680 [INFO] [OK] subscription V113063101 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:47,928 [INFO] [OK] subscription V113063119 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:49,181 [INFO] [OK] subscription V113063127 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:50,430 [INFO] [OK] subscription V113063135 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:51,559 [INFO] [OK] subscription V113063143 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:52,795 [INFO] [OK] subscription V113063150 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:54,042 [INFO] [OK] subscription V113063184 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:55,333 [INFO] [OK] subscription V113063192 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:56,487 [INFO] [OK] subscription V113063226 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:57,747 [INFO] [OK] subscription V113063234 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:06:58,904 [INFO] [OK] subscription V113063242 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:00,082 [INFO] [OK] subscription V113063275 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:01,211 [INFO] [OK] subscription V113064414 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:02,434 [INFO] [OK] subscription V113063291 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:03,817 [INFO] [OK] subscription V113063838 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:04,954 [INFO] [OK] subscription V113064091 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:06,220 [INFO] [OK] subscription V113064109 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:07,594 [INFO] [OK] subscription V113064117 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:08,729 [INFO] [OK] subscription V113064141 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:09,977 [INFO] [OK] subscription V113064505 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:11,237 [INFO] [OK] subscription V113064315 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:12,497 [INFO] [OK] subscription V113064364 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:13,738 [INFO] [OK] subscription V113064430 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:14,862 [INFO] [OK] subscription V113064307 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:16,105 [INFO] [OK] subscription V113064513 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:17,244 [INFO] [OK] subscription V113064406 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:18,414 [INFO] [OK] subscription V113064463 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:19,569 [INFO] [OK] subscription V113064539 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:20,903 [INFO] [OK] subscription V113064547 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:22,059 [INFO] [OK] subscription V113064323 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:23,312 [INFO] [OK] subscription V113064455 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:24,384 [INFO] [OK] subscription V113066245 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:25,515 [INFO] [OK] subscription V113064398 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:25,518 [INFO] Progress: 50/247 — 50 succeeded so far
2026-07-27 11:07:26,583 [INFO] [OK] subscription V113066252 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:27,720 [INFO] [OK] subscription V113064331 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:28,892 [INFO] [OK] subscription V113066260 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:29,971 [INFO] [OK] subscription V113064422 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:31,049 [INFO] [OK] subscription V113066286 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:32,174 [INFO] [OK] subscription V113064356 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:33,248 [INFO] [OK] subscription V113066294 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:34,379 [INFO] [OK] subscription V113064448 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:35,492 [INFO] [OK] subscription V113066427 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:36,580 [INFO] [OK] subscription V113064471 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:37,653 [INFO] [OK] subscription V113066476 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:38,719 [INFO] [OK] subscription V113064497 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:39,863 [INFO] [OK] subscription V113066484 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:40,979 [INFO] [OK] subscription V113066237 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:42,092 [INFO] [OK] subscription V113066526 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:43,220 [INFO] [OK] subscription V113066393 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:44,281 [INFO] [OK] subscription V113066708 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:45,413 [INFO] [OK] subscription V113066401 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:46,543 [INFO] [OK] subscription V113066716 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:47,668 [INFO] [OK] subscription V113067607 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:48,791 [INFO] [OK] subscription V113066757 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:49,858 [INFO] [OK] subscription V113068233 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:50,931 [INFO] [OK] subscription V113067102 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:51,999 [INFO] [OK] subscription V113068290 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:53,191 [INFO] [OK] subscription V113068308 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:54,429 [INFO] [OK] subscription V113068258 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:55,679 [INFO] [OK] subscription V113068357 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:56,925 [INFO] [OK] subscription V113068761 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:58,179 [INFO] [OK] subscription V113068423 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:07:59,432 [INFO] [OK] subscription V113068662 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:00,561 [INFO] [OK] subscription V113068787 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:01,851 [INFO] [OK] subscription V113068795 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:02,995 [INFO] [OK] subscription V113068803 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:04,166 [INFO] [OK] subscription V113068829 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:05,331 [INFO] [OK] subscription V113069207 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:06,578 [INFO] [OK] subscription V113069215 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:07,826 [INFO] [OK] subscription V113069066 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:09,068 [INFO] [OK] subscription V113069074 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:10,315 [INFO] [OK] subscription V113069439 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:11,472 [INFO] [OK] subscription V113069595 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:12,726 [INFO] [OK] subscription V113069629 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:13,861 [INFO] [OK] subscription V113069918 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:15,131 [INFO] [OK] subscription V113070445 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:16,348 [INFO] [OK] subscription V113070452 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:17,594 [INFO] [OK] subscription V113070460 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:18,662 [INFO] [OK] subscription V113070833 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:19,738 [INFO] [OK] subscription V113070478 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:20,810 [INFO] [OK] subscription V113071138 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:21,936 [INFO] [OK] subscription V113070486 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:23,001 [INFO] [OK] subscription V113071153 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:23,003 [INFO] Progress: 100/247 — 100 succeeded so far
2026-07-27 11:08:24,112 [INFO] [OK] subscription V113070494 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:25,274 [INFO] [OK] subscription V113071179 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:26,392 [INFO] [OK] subscription V113070429 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:27,512 [INFO] [OK] subscription V113071146 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:28,580 [INFO] [OK] subscription V113070437 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:29,657 [INFO] [OK] subscription V113071161 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:30,725 [INFO] [OK] subscription V113070502 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:31,860 [INFO] [OK] subscription V113071187 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:32,935 [INFO] [OK] subscription V113070510 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:34,025 [INFO] [OK] subscription V113071906 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:35,120 [INFO] [OK] subscription V113070775 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:36,197 [INFO] [OK] subscription V113071922 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:37,326 [INFO] [OK] subscription V113070957 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:38,442 [INFO] [OK] subscription V113072029 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:39,555 [INFO] [OK] subscription V113071302 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:40,616 [INFO] [OK] subscription V113072441 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:41,695 [INFO] [OK] subscription V113072458 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:42,827 [INFO] [OK] subscription V113072623 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:43,945 [INFO] [OK] subscription V113073217 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:45,078 [INFO] [OK] subscription V113072649 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:46,144 [INFO] [OK] subscription V113073225 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:47,215 [INFO] [OK] subscription V113072664 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:48,343 [INFO] [OK] subscription V113073241 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:49,460 [INFO] [OK] subscription V113072631 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:50,522 [INFO] [OK] subscription V113073274 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:51,593 [INFO] [OK] subscription V113072656 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:52,663 [INFO] [OK] subscription V113073282 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:53,785 [INFO] [OK] subscription V113073894 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:54,859 [INFO] [OK] subscription V113073290 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:55,981 [INFO] [OK] subscription V113074017 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:57,096 [INFO] [OK] subscription V113073233 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:58,200 [INFO] [OK] subscription V113073985 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:08:59,278 [INFO] [OK] subscription V113073258 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:00,427 [INFO] [OK] subscription V113073993 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:01,610 [INFO] [OK] subscription V113074082 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:02,755 [INFO] [OK] subscription V113074009 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:03,874 [INFO] [OK] subscription V113074090 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:04,943 [INFO] [OK] subscription V113074108 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:06,071 [INFO] [OK] subscription V113076103 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:07,193 [INFO] [OK] subscription V113074660 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:08,318 [INFO] [OK] subscription V113076319 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:09,396 [INFO] [OK] subscription V113075584 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:10,468 [INFO] [OK] subscription V113076418 -> 99965692_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:11,590 [INFO] [OK] subscription V113075618 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:12,841 [INFO] [OK] subscription V113075782 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:14,095 [INFO] [OK] subscription V113076814 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:15,245 [INFO] [OK] subscription V113078026 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:16,489 [INFO] [OK] subscription V113078000 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:17,745 [INFO] [OK] subscription V113078133 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:18,989 [INFO] [OK] subscription V113078141 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:18,992 [INFO] Progress: 150/247 — 150 succeeded so far
2026-07-27 11:09:20,122 [INFO] [OK] subscription V113078166 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:21,388 [INFO] [OK] subscription V113078174 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:22,559 [INFO] [OK] subscription V113078158 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:23,721 [INFO] [OK] subscription V113078182 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:24,892 [INFO] [OK] subscription V113078190 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:26,226 [INFO] [OK] subscription V113078208 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:27,532 [INFO] [OK] subscription V113078216 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:28,816 [INFO] [OK] subscription V113078224 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:29,958 [INFO] [OK] subscription V113078307 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:31,234 [INFO] [OK] subscription V113079289 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:32,372 [INFO] [OK] subscription V113079297 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:33,621 [INFO] [OK] subscription V113079321 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:34,881 [INFO] [OK] subscription V113079339 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)
2026-07-27 11:09:36,136 [INFO] [OK] subscription V113079347 -> 999656921_fullbatch5 (plan_matched=True, orderId=unknown)

,SubscriptionUSN,TargetAccountNumber,status,plan_matched,productName,priceplanName,onebill_order_id,error
0,V113062392,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (TFF),WS Tail+Data - BS2 Res Fibre Starter (TFF) - 1...,unknown,None
1,V113063044,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
2,V113063085,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
3,V113063036,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
4,V113062996,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
5,V113061451,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Enable),WS Tail+Data - BS2 Res (Enable) - 920/500,unknown,None
6,V113062384,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (TFF),WS Tail+Data - BS2 Res Fibre Starter (TFF) - 1...,unknown,None
7,V113063002,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
8,V113063051,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
9,V113063010,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
10,V113063168,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
11,V113063176,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res (Chorus) - 920/500,unknown,None
12,V113063200,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res (Chorus) - 920/500,unknown,None
13,V113063218,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
14,V113063028,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
15,V113063069,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
16,V113063093,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
17,V113063101,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
18,V113063119,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None
19,V113063127,99965692_fullbatch5,success,True,Wholesale Fibre BS2 (Chorus),WS Tail+Data - BS2 Res Fibre Starter (Chorus) ...,unknown,None

## 8. Save

In [16]:
save_df("order_results", order_results_df)

Saved 247 rows -> migration_data\07_order_creation_results.csv